spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  datasource:
    url: jdbc:postgresql://localhost:5432/as-data?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: postgres
    password: abcd1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.localhost:8080
server:
  port: 7070

logging:
  level:
    root: info
    org.springframework.security.*: TRACE

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
