spring:

  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  datasource:
    url: jdbc:postgresql://localhost:5432/as-data?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: postgres
    password: abcd1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: true

  security:
    oauth2:
      client:

        registration:
          licky-client-oidc:
            provider: licky-auth-server
            client-id: licky-client-oidc
            client-secret: licky-password
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://client.localhost:9090/login/oauth2/code/client-demo-oidc
            client-name: licky-client-oidc
          licky-client:
            provider: licky-auth-server
            client-id: licky-client
            client-secret: licky-password
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://client.localhost:9090/authorized
            client-name: licky-client
        provider:
          licky-auth-server:
            issuer-uri: http://auth.localhost:8080
#            authorization-uri: http://auth.localhost:8080/oauth2/v1/authorize
#            token-uri: http://auth.localhost:8080/oauth2/v1/token
#            jwk-set-uri: http://localhost:8080/oauth2/v1/jwks
#            user-info-uri: http://localhost:8080/connect/v1/userinfo
#            user-info-authentication-method: none
#            user-name-attribute: username
server:
  port: 9090

logging:
  level:
    root: info
    org.springframework.security.*: TRACE

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
