spring:

  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  datasource:
    url: jdbc:postgresql://localhost:5433/client-data?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: postgres
    password: abcd1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    open-in-view: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  security:
    oauth2:
      client:

        registration:
          # 用于测试 oauth2-client_credentials 方式认证
          licky-client-credentials:
            provider: licky-auth-server
            client-id: licky-client-credentials
            client-secret: licky-credentials-password
            scope: read,write,user.register,user.update,user.delete
            authorization-grant-type: client_credentials
            redirect-uri: http://client.localhost:9090/credentials
            client-name: licky-client-credentials
          # 用于测试 OIDC 登陆
          licky-client-oidc:
            provider: licky-auth-server
            client-id: licky-client-oidc
            client-secret: licky-oidc-password
            scope: openid,read,write,email,phone,address,profile
            authorization-grant-type: authorization_code
            redirect-uri: http://client.localhost:9090/oidc/authorized
            client-name: licky-client-oidc
          # 用于测试 oauth2-authorization_code 认证
          licky-client:
            provider: licky-auth-server
            client-id: licky-client
            client-secret: licky-password
            client-authentication-method: client_secret_post
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://client.localhost:9090/client/authorized
            client-name: licky-client
          # 用于 OIDC Client Registration
          dev-client:
            provider: licky-auth-server
            client-id: dev-client
            client-secret: dev-client-password
            client-name: dev-client
            scope: client.create
            authorization-grant-type: client_credentials
            redirect-uri: http://client.localhost:9090/oidc/dev-client
        provider:
          licky-auth-server:
            issuer-uri: http://auth.localhost:8080
server:
  port: 9090

logging:
  level:
    root: info
    org.springframework.security.*: TRACE
